// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Peers is a list of peer's network address.
type Peers struct {
	Peers                []string `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peers) Reset()         { *m = Peers{} }
func (m *Peers) String() string { return proto.CompactTextString(m) }
func (*Peers) ProtoMessage()    {}
func (*Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_816266a3e45e4356, []int{0}
}
func (m *Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peers.Unmarshal(m, b)
}
func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peers.Marshal(b, m, deterministic)
}
func (dst *Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peers.Merge(dst, src)
}
func (m *Peers) XXX_Size() int {
	return xxx_messageInfo_Peers.Size(m)
}
func (m *Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Peers)(nil), "p2p.Peers")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerServiceClient interface {
	// GetNeighbors returns the already known neighbor peers.
	GetNeighbors(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Peers, error)
}

type peerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPeerServiceClient(cc *grpc.ClientConn) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) GetNeighbors(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Peers, error) {
	out := new(Peers)
	err := c.cc.Invoke(ctx, "/p2p.PeerService/GetNeighbors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
type PeerServiceServer interface {
	// GetNeighbors returns the already known neighbor peers.
	GetNeighbors(context.Context, *wrappers.StringValue) (*Peers, error)
}

func RegisterPeerServiceServer(s *grpc.Server, srv PeerServiceServer) {
	s.RegisterService(&_PeerService_serviceDesc, srv)
}

func _PeerService_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p.PeerService/GetNeighbors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).GetNeighbors(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _PeerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNeighbors",
			Handler:    _PeerService_GetNeighbors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	// ReceiveMessage receives message from a peer.
	ReceiveMessage(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*any.Any, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) ReceiveMessage(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*any.Any, error) {
	out := new(any.Any)
	err := c.cc.Invoke(ctx, "/p2p.MessageService/ReceiveMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	// ReceiveMessage receives message from a peer.
	ReceiveMessage(context.Context, *any.Any) (*any.Any, error)
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(any.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p.MessageService/ReceiveMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ReceiveMessage(ctx, req.(*any.Any))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _MessageService_ReceiveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeServiceClient interface {
	// ReceiveBroadcast receives message and broadcasts it to neighbor peers.
	ReceiveBroadcast(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*any.Any, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) ReceiveBroadcast(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*any.Any, error) {
	out := new(any.Any)
	err := c.cc.Invoke(ctx, "/p2p.NodeService/ReceiveBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
type NodeServiceServer interface {
	// ReceiveBroadcast receives message and broadcasts it to neighbor peers.
	ReceiveBroadcast(context.Context, *any.Any) (*any.Any, error)
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_ReceiveBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(any.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReceiveBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p.NodeService/ReceiveBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReceiveBroadcast(ctx, req.(*any.Any))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveBroadcast",
			Handler:    _NodeService_ReceiveBroadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_p2p_816266a3e45e4356) }

var fileDescriptor_p2p_816266a3e45e4356 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xce, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0x06, 0x70, 0xe4, 0x50, 0xb8, 0x77, 0x72, 0x48, 0xb8, 0x41, 0x83, 0x8a, 0x38, 0x39, 0xa5,
	0x10, 0x17, 0x07, 0x11, 0x74, 0xe9, 0xd4, 0x22, 0x2d, 0xb8, 0xa7, 0xed, 0x33, 0x06, 0x4a, 0x13,
	0x5e, 0xd2, 0x4a, 0xff, 0x7b, 0x69, 0xd3, 0x3a, 0xa8, 0x8b, 0xdb, 0xfb, 0xbe, 0x2f, 0xfc, 0x08,
	0x6c, 0x9d, 0x74, 0xc2, 0x91, 0x0d, 0x96, 0x6d, 0x9c, 0x74, 0xfc, 0x5a, 0x5b, 0xab, 0x5b, 0x4c,
	0xe6, 0xaa, 0xea, 0xdf, 0x93, 0x4f, 0x52, 0xce, 0x21, 0xf9, 0xf8, 0x88, 0x5f, 0xfc, 0xdc, 0x55,
	0x37, 0xc6, 0xe9, 0xf6, 0x0a, 0x8e, 0x5f, 0x11, 0xc9, 0xb3, 0xc3, 0x72, 0x9c, 0x1f, 0xdd, 0x6c,
	0xee, 0xb6, 0x45, 0x0c, 0x32, 0x85, 0xdd, 0x74, 0x94, 0x48, 0x83, 0xa9, 0x91, 0x3d, 0xc0, 0x69,
	0x8a, 0x21, 0x47, 0xa3, 0x3f, 0x2a, 0x4b, 0x9e, 0x5d, 0x8a, 0x28, 0x8b, 0x55, 0x16, 0x65, 0x20,
	0xd3, 0xe9, 0x37, 0xd5, 0xf6, 0xc8, 0x41, 0x4c, 0xff, 0x8c, 0x50, 0x0e, 0xfb, 0x0c, 0xbd, 0x57,
	0x1a, 0x57, 0xeb, 0x11, 0xf6, 0x05, 0xd6, 0x68, 0x06, 0x5c, 0x06, 0x76, 0xf8, 0xa5, 0x3d, 0x77,
	0x23, 0xff, 0xb3, 0x95, 0x19, 0xec, 0x72, 0xdb, 0x7c, 0x63, 0x4f, 0x70, 0xb6, 0x60, 0x2f, 0x64,
	0x55, 0x53, 0x2b, 0x1f, 0xfe, 0xc3, 0x55, 0x27, 0x73, 0xba, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x7a, 0x1a, 0x3e, 0x4a, 0x5a, 0x01, 0x00, 0x00,
}
